[project]
name = "chatbot-rag-devia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.11.1",
    "chromadb>=1.5.8",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "marker-pdf>=1.10.2",
    "pymupdf4llm>=1.27.2.3",
    "python-dotenv>=1.2.2",
]
